### ISSUE TITLE
thunar no longer respects theme

### ISSUE THREAD

**Issue by andrewfader** [lassekongo83/adw-colors#30]
Something I recently updated now gives me ugly white adwaita in thunar.

Not sure if related, but I see this when I open it:
```
❯ thunar

(thunar:10499): Gtk-WARNING **: 00:55:46.760: Theme parsing error: gtk.css:23:40: Expected ',' in color definition

(thunar:10499): Gtk-WARNING **: 00:55:46.760: Theme parsing error: gtk.css:24:41: Expected ',' in color definition

(thunar:10499): Gtk-WARNING **: 00:55:46.760: Theme parsing error: gtk.css:51:1: Invalid name of pseudo-class

```

**Comment by lassekongo83** [comment]
You didn't specify which of the themes you use.

**Comment by andrewfader** [comment]
Oh sorry.  adw-colors/themes/solarized-dark/gtk.css

**Comment by lassekongo83** [comment]
Fixed. Copy `gtk4.css` to `~/.config/gtk-4.0/gtk.css` and `gtk3.css` to `~/.config/gtk-3.0/gtk.css`

**Comment by andrewfader** [comment]
@lassekongo83 this fixes the warning, but I still do not see a solarized dark theme in thunar. Is there something else I should do?

**Comment by lassekongo83** [comment]
How is thunar installed? Repo, flatpak, snap, distrobox, or something else? If you run `printenv` is there any `GTK_THEME` variable set? (If there is, then run `unset GTK_THEME`).

**Comment by andrewfader** [comment]
Thunar installed from the arch official repos. No GTK_THEME. I have a similar problem with the xfce4 terminal and tranmission-remote-gtk. Everything worked until a day or two again when new updates to something were installed. I do install packages from the arch testing and the cachyos repos, but these don't seem to have affected those packages. But maybe affect a dependency?
```
❯ pacman -Q thunar
thunar 4.20.1-1
❯ echo $GTK_THEME

❯ printenv | grep GTK
❯ printenv | grep XDG
XDG_ACTIVATION_TOKEN=gnome-shell/Xfce Terminal/7544-2-obsidian_TIME29543936
XDG_SESSION_TYPE=wayland
XDG_SESSION_DESKTOP=gnome
XDG_RUNTIME_DIR=/run/user/1000
XDG_CURRENT_DESKTOP=GNOME
XDG_SESSION_CLASS=user
XDG_MENU_PREFIX=gnome-
```

**Comment by andrewfader** [comment]
Noticed that nwg-look lists adw-gtk3-dark but lxappearance does not. A clue?

**Comment by andrewfader** [comment]
Actually, the problem isn't limited to adw-gtk3 or adw-colors since it won't respect any theme I choose not just that one. So I guess rightfully closed issue. Thanks.
